name: financial_ai_mobile
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  dots_indicator: ^4.0.1
  flutter_svg: ^2.0.17
  flutter_otp_text_field: ^1.5.1+1
  flutter_floating_bottom_bar: ^1.2.1+1
  awesome_bottom_bar: ^1.2.4
  fl_chart: ^0.70.2
  percent_indicator: ^4.2.4
  syncfusion_flutter_charts: ^28.2.11
  cli_table: ^1.0.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  mime: ^2.0.0
  shimmer: ^3.0.0
  typethis: ^1.0.3
  flutter_markdown: ^0.7.7
  flutter_dotenv: ^5.2.1
  speech_to_text: ^7.0.0
  permission_handler: ^12.0.0+1
  animate_do: ^4.2.0
  custom_refresh_indicator: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/